export RED := $(shell tput setaf 1)
export GRN := $(shell tput setaf 2)
export YLW := $(shell tput setaf 3)
export BLU := $(shell tput setaf 4)
export MAG := $(shell tput setaf 5)
export CYN := $(shell tput setaf 6)
export WHT := $(shell tput setaf 7)
export RST := $(shell tput sgr0)